package com.customblocks.gui;

/**
 * All GUI modes / screens.
 */
public enum GuiMode {
    MAIN,
    PICKER,
    PICKER_BROKEN,
    EDITOR,
    FACE_EDITOR,
    FACE_CHANGE_SELECT,
    FACE_CHANGE_PICKER,
    SHAPE_EDITOR,
    MAINTENANCE_MENU,
    HELP_MENU,
    TOOLS_GUI,
    PROPERTIES_MENU,
    SOUND_MENU,
    ANIM_GUI,
    TAB_ICON_MENU,
    FIND_PORT_GUI,
    RESOURCE_CENTER,
    BULK_DELETE,
    SEARCH_PICKER,
    MAGIC_ITEMS,
    UNDO_PICKER,
    CONFIG_WARNING,
    CONFIG_GUI,
    HELP_CATEGORY,
    ANIM_CONFIRM_ABANDON,
    BG_STUDIO,
    QUICK_ACTIONS,
    COLOR_STUDIO,
    EDIT_MAGIC_ITEMS
}
